/**
 * API V3 - Administration
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSearchResponse } from './userSearchResponse';
import { PaginationMeta } from './paginationMeta';


export interface APISuccessListUserSearchResponse { 
    code: number;
    success?: boolean | null;
    timestamp?: string;
    message?: string | null;
    data?: Array<UserSearchResponse> | null;
    pagination: PaginationMeta | null;
}

