/**
 * API V3 - Administration
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginationMeta } from './paginationMeta';
import { PreferenceResponse } from './preferenceResponse';


export interface APISuccessPreferenceResponse { 
    code: number;
    success?: boolean | null;
    timestamp?: string;
    message?: string | null;
    data?: PreferenceResponse | null;
    pagination: PaginationMeta | null;
}

