/**
 * API V3 - Administration
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PreferenceResponse } from './preferenceResponse';


/**
 * Modèle de réponse pour la liste des préférences d\'un utilisateur.
 */
export interface PreferencesListResponse { 
    /**
     * Préférences créées par l\'utilisateur
     */
    create_by_user?: Array<PreferenceResponse>;
    /**
     * Préférences partagées avec l\'utilisateur
     */
    shared_with_user?: Array<PreferenceResponse>;
}

