/**
 * API V3 - Administration
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShareResponse } from './shareResponse';


/**
 * Modèle de réponse pour une préférence.
 */
export interface PreferenceResponse { 
    /**
     * Identifiant unique de la préférence
     */
    uuid: string;
    /**
     * Nom d\'utilisateur du créateur de la préférence
     */
    username: string;
    /**
     * Nom de la préférence
     */
    name: string;
    /**
     * Critères de filtrage en format JSON
     */
    filters: { [key: string]: any; };
    options?: { [key: string]: any; } | null;
    /**
     * Liste des partages de cette préférence
     */
    shares?: Array<ShareResponse>;
    /**
     * Nombre de fois que la préférence a été utilisée
     */
    nombre_utilisation?: number;
    dernier_acces?: string | null;
    /**
     * Client ID de l\'application
     */
    application_clientid: string;
    date_creation?: string | null;
}

