/**
 * API V3 - Administration
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShareRequest } from './shareRequest';


/**
 * Modèle de requête pour la mise à jour d\'une préférence.
 */
export interface PreferenceUpdateRequest { 
    /**
     * Nom de la préférence
     */
    name: string;
    /**
     * Critères de filtrage en format JSON
     */
    filters: { [key: string]: any; };
    options?: { [key: string]: any; } | null;
    /**
     * Liste des utilisateurs avec qui partager
     */
    shares?: Array<ShareRequest>;
}

