/**
 * API V3 - Administration
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Modèle de requête pour le partage d\'une préférence.
 */
export interface ShareRequest { 
    /**
     * Email de l\'utilisateur avec qui partager la préférence
     */
    shared_username_email: string;
}

