/**
 * API V3 - Administration
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Modèle de réponse pour un partage de préférence.
 */
export interface ShareResponse { 
    /**
     * Email de l\'utilisateur
     */
    shared_username_email: string;
    /**
     * Indique si l\'email de notification a été envoyé
     */
    email_send?: boolean;
    date_email_send?: string | null;
}

