/**
 * API V3 - Administration
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Modèle de réponse pour la recherche d\'utilisateurs Keycloak.
 */
export interface UserSearchResponse { 
    /**
     * Nom d\'utilisateur Keycloak
     */
    username: string;
}

