
export enum ColonneLibelles {
  SOURCE = "Source de données",
  N_EJ = "N° EJ",
  POSTE_EJ = "N° Poste EJ",
  MONTANT_AE = "Montant engagé",
  MONTANT_CP = "Montant payé",
  THEME = "Thème",
  CODE_PROGRAMME = "Code programme",
  PROGRAMME = "Programme",
  CODE_DOMAINE = "Code domaine fonctionnel",
  DOMAINE = "Domaine fonctionnel",
  REFERENTIEL_PROGRAMMATION = "Ref Programmation",
  COMMUNE = "Commune du SIRET",
  CRTE = "CRTE du SIRET",
  EPCI = "EPCI du SIRET",
  ARRONDISSEMENT = "Arrondissement du SIRET",
  DEPARTEMENT = "Département du SIRET",
  REGION = "Région du SIRET",
  CODE_LOC_INTER = "Code localisation interministérielle",
  LOC_INTER = "Localisation interministérielle",
  COMPTE_BUDGETAIRE = "Compte budgétaire",
  CPER = "CPER",
  CODE_GROUPE_MARCHANDISE = "Code groupe marchandise",
  GROUPE_MARCHANDISE = "Groupe marchandise",
  SIRET = "Siret",
  BENEFICIAIRE = "Bénéficiaire",
  TYPE_ETABLISSEMENT = "Type d'établissement",
  CODE_QPV = "Code QPV",
  QPV = "QPV",
  DATE_DERNIER_PAIEMENT = "Date dernier paiement",
  DATE_CREATION_EJ = "Date création EJ",
  ANNEE_ENGAGEMENT = "Année Exercice Comptable",
  CODE_CENTRE_COUTS = "Code centre coûts",
  LABEL_CENTRE_COUTS = "Label centre coûts",
  CENTRE_COUTS = "Centre coûts",
  TAGS = "Tags",
}
