"🐣 deploy fronts on integration":
  stage: "🐣 deploy"
  trigger:
    project: SIBSGAR/DataRegateNum/stack
    branch: main
    forward:
      yaml_variables: true
      pipeline_variables: false
  variables: 
    DO_DEPLOY: "✅"
    DO_DEPLOY_environment: "integ"
  when: manual

"🚨 deploy fronts on preprod":
  stage: "🐣 deploy"
  trigger:
    project: SIBSGAR/DataRegateNum/stack
    branch: main
    forward:
      yaml_variables: true
      pipeline_variables: false
  variables:
    DO_DEPLOY: "✅"
    DO_DEPLOY_environment: "preprod"
  rules:
    - if: '$_ENABLE_DEPLOY_FOR_PP_AND_P == "✅"'
      when: manual
    - when: never

"🚨 deploy fronts on prod":
  stage: "🐣 deploy"
  trigger:
    project: SIBSGAR/DataRegateNum/stack
    branch: main
    forward:
      yaml_variables: true
      pipeline_variables: false
  variables:
    DO_DEPLOY: "✅"
    DO_DEPLOY_environment: "prod"
  rules:
    - if: '$_ENABLE_DEPLOY_FOR_PP_AND_P == "✅"'
      when: manual
    - when: never