"🐣 deploy fronts on integration":
  stage: "🐣 deploy"
  trigger:
    project: SIBSGAR/DataRegateNum/stack
    branch: main
    forward:
      yaml_variables: true
      pipeline_variables: false
    strategy: depend
  variables: 
    DO_DEPLOY: "✅"
    DO_DEPLOY_environment: "integ"
    UPSTREAM_PROJECT: $CI_PROJECT_PATH
  rules:
    - if: '$_ENABLE_DEPLOY_FOR_INTEG == "✅"'
      when: always
    - when: manual

"🚨 deploy fronts on preprod":
  stage: "🐣 deploy"
  trigger:
    project: SIBSGAR/DataRegateNum/stack
    branch: main
    forward:
      yaml_variables: true
      pipeline_variables: false
  variables:
    DO_DEPLOY: "✅"
    DO_DEPLOY_environment: "preprod"
    UPSTREAM_PROJECT: $CI_PROJECT_PATH
  rules:
    - if: '$_ENABLE_DEPLOY_FOR_PP_AND_P == "✅"'
      when: manual
    - when: never

"🚨 deploy fronts on prod":
  stage: "🐣 deploy"
  trigger:
    project: SIBSGAR/DataRegateNum/stack
    branch: main
    forward:
      yaml_variables: true
      pipeline_variables: false
  variables:
    DO_DEPLOY: "✅"
    DO_DEPLOY_environment: "prod"
    UPSTREAM_PROJECT: $CI_PROJECT_PATH
  rules:
    - if: '$_ENABLE_DEPLOY_FOR_PP_AND_P == "✅"'
      when: manual
    - when: never