include:
  - project: SIBSGAR/DataRegateNum/common-gitlab-templates
    ref: main
    file: product-skeleton.gitlab-ci.yml
  - .gitlab-templates/build.gitlab-ci.yml
  - .gitlab-templates/dockerize.gitlab-ci.yml
  - .gitlab-templates/deploy.gitlab-ci.yml
  - .gitlab-templates/integ-tests.gitlab-ci.yml

variables:
  PYTHON_IMAGE: python:3.12.6-slim
  # XXX: Important to reference internal variables into custom ones here
  # to support variable passing to downward pipeline
  _TAG_VER: $CI_COMMIT_TAG
  _SNAP_VER: ${CI_COMMIT_SHORT_SHA}-snapshot
  DO_DEPLOY_tags: "fronts"
  _ENABLE_DEPLOY_FOR_PP_AND_P: "❌"
  _ENABLE_DEPLOY_FOR_INTEG: "❌"
  # XXX shadowing template variables as it is unused as user input in pipeline
  DO_BUILD: "✅"
  DO_INTEG_TESTS: "❌"
  DO_DEPLOY: "❌" 
  DO_DOCKERIZE: "❌"
  DO_TEST: "❌"
  DO_ANALYZE: "❌"

workflow:
  rules:
    - if: "$CI_COMMIT_TAG"
      variables:
        _ENABLE_DEPLOY_FOR_PP_AND_P: "✅"
        DO_BUILD: "✅"
        DO_DOCKERIZE: "✅"
        FRONTS_VER: $_TAG_VER
        DO_DEPLOY_extra_vars: FRONTS_VER=$FRONTS_VER
        DO_UPDATE_FRONTS_VER: "$FRONTS_VER"
    - if: '$CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME == "develop" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        FRONTS_VER: "$_SNAP_VER"
        DO_DEPLOY_extra_vars: 'FRONTS_VER="$FRONTS_VER"'
        _ENABLE_DEPLOY_FOR_INTEG: "✅"
        DO_INTEG_TESTS: "✅"
        DO_BUILD: "✅"
        DO_DOCKERIZE: "✅"
    - if: "$CI_COMMIT_REF_NAME" # always passing
      variables:
        FRONTS_VER: "$_SNAP_VER"
        DO_BUILD: "❌"
        DO_DEPLOY_extra_vars: 'FRONTS_VER="$FRONTS_VER"'
