/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupedData } from './groupedData';
import { Groupings } from './groupings';
import { Total } from './total';
import { EnrichedFlattenFinancialLines2 } from './enrichedFlattenFinancialLines2';
import { LignesFinancieres } from './lignesFinancieres';


export interface Data { 
    type?: Data.TypeEnum;
    total: Total;
    lignes: Array<EnrichedFlattenFinancialLines2>;
    groupings: Array<GroupedData>;
}
export namespace Data {
    export type TypeEnum = 'lignes_financieres' | 'groupings';
    export const TypeEnum = {
        LignesFinancieres: 'lignes_financieres' as TypeEnum,
        Groupings: 'groupings' as TypeEnum
    };
}


