/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DetailsPaiement } from './detailsPaiement';


export interface DetailsPaiementResponse { 
    ligne_financiere_id: number;
    dps: Array<DetailsPaiement>;
}

