/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Un détail de paiement pour l\'API
 */
export interface DetailsPaiement { 
    date_base_dp: string | null;
    montant: number;
    n_dp: string;
}

