/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginationMeta } from './paginationMeta';
import { ExportFinancialTask } from './exportFinancialTask';


export interface DoExportResponse { 
    code: number;
    success?: boolean | null;
    timestamp?: string;
    message?: string | null;
    data?: ExportFinancialTask | null;
    pagination: PaginationMeta | null;
}

