/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tags } from './tags';


/**
 * dict() -> new empty dictionary dict(mapping) -> new dictionary initialized from a mapping object\'s     (key, value) pairs dict(iterable) -> new dictionary initialized as if via:     d = {}     for k, v in iterable:         d[k] = v dict(**kwargs) -> new dictionary initialized with the name=value pairs     in the keyword argument list.  For example:  dict(one=1, two=2)
 */
export interface EnrichedFlattenFinancialLines { 
    source?: EnrichedFlattenFinancialLines.SourceEnum | null;
    id: number;
    n_ej?: string | null;
    n_poste_ej?: number | null;
    annee?: number | null;
    contrat_etat_region?: string | null;
    compte_budgetaire?: string | null;
    montant_ae?: number | null;
    montant_cp?: number | null;
    dateDeDernierPaiement?: string | null;
    dateDeCreation?: string | null;
    domaineFonctionnel_code?: string | null;
    domaineFonctionnel_label?: string | null;
    referentielProgrammation_code?: string | null;
    referentielProgrammation_label?: string | null;
    groupeMarchandise_code?: string | null;
    groupeMarchandise_label?: string | null;
    programme_code?: string | null;
    programme_label?: string | null;
    programme_theme?: string | null;
    beneficiaire_code?: string | null;
    beneficiaire_denomination?: string | null;
    beneficiaire_categorieJuridique_type?: string | null;
    beneficiaire_qpv_code?: string | null;
    beneficiaire_qpv_label?: string | null;
    beneficiaire_qpv24_code?: string | null;
    beneficiaire_qpv24_label?: string | null;
    beneficiaire_commune_code?: string | null;
    beneficiaire_commune_label?: string | null;
    beneficiaire_commune_codeRegion?: string | null;
    beneficiaire_commune_labelRegion?: string | null;
    beneficiaire_commune_codeDepartement?: string | null;
    beneficiaire_commune_labelDepartement?: string | null;
    beneficiaire_commune_codeEpci?: string | null;
    beneficiaire_commune_labelEpci?: string | null;
    beneficiaire_commune_codeCrte?: string | null;
    beneficiaire_commune_labelCrte?: string | null;
    beneficiaire_commune_arrondissement_code?: string | null;
    beneficiaire_commune_arrondissement_label?: string | null;
    localisationInterministerielle_code?: string | null;
    localisationInterministerielle_label?: string | null;
    localisationInterministerielle_codeDepartement?: string | null;
    localisationInterministerielle_commune_code?: string | null;
    localisationInterministerielle_commune_label?: string | null;
    localisationInterministerielle_commune_codeRegion?: string | null;
    localisationInterministerielle_commune_labelRegion?: string | null;
    localisationInterministerielle_commune_codeDepartement?: string | null;
    localisationInterministerielle_commune_labelDepartement?: string | null;
    localisationInterministerielle_commune_codeEpci?: string | null;
    localisationInterministerielle_commune_labelEpci?: string | null;
    localisationInterministerielle_commune_codeCrte?: string | null;
    localisationInterministerielle_commune_labelCrte?: string | null;
    localisationInterministerielle_commune_arrondissement_code?: string | null;
    localisationInterministerielle_commune_arrondissement_label?: string | null;
    source_region?: string | null;
    updated_at?: string | null;
    created_at?: string | null;
    centreCouts_code?: string | null;
    centreCouts_label?: string | null;
    centreCouts_description?: string | null;
    data_source?: string | null;
    lieu_action_code_qpv?: string | null;
    lieu_action_label_qpv?: string | null;
    date_modification?: string | null;
    tags?: Array<Tags> | null;
}
export namespace EnrichedFlattenFinancialLines {
    export type SourceEnum = 'FINANCIAL_DATA_AE' | 'FINANCIAL_DATA_CP' | 'FRANCE_RELANCE' | 'FRANCE_2030' | 'ADEME' | 'REFERENTIEL';
    export const SourceEnum = {
        FinancialDataAe: 'FINANCIAL_DATA_AE' as SourceEnum,
        FinancialDataCp: 'FINANCIAL_DATA_CP' as SourceEnum,
        FranceRelance: 'FRANCE_RELANCE' as SourceEnum,
        France2030: 'FRANCE_2030' as SourceEnum,
        Ademe: 'ADEME' as SourceEnum,
        Referentiel: 'REFERENTIEL' as SourceEnum
    };
}


