/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO pour l\'entité ExportFinancialTask.
 */
export interface ExportFinancialTask { 
    username: string;
    prefect_run_id: string;
    target_format: string;
    status: string;
    name: string;
    started_at: string;
    completed_at: string;
}

