/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Colonne1 } from './colonne1';


export interface GroupedData { 
    colonne: Colonne1;
    total: number;
    total_montant_engage?: number;
    total_montant_paye?: number;
}

