/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupedData } from './groupedData';


export interface Groupings { 
    type?: Groupings.TypeEnum;
    groupings: Array<GroupedData>;
}
export namespace Groupings {
    export type TypeEnum = 'groupings';
    export const TypeEnum = {
        Groupings: 'groupings' as TypeEnum
    };
}


