/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Label } from './label';
import { Value } from './value';


export interface GroupedData { 
    colonne?: string;
    label: Label | null;
    value: Value | null;
    total: number;
    total_montant_engage?: number;
    total_montant_paye?: number;
}

