/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnrichedFlattenFinancialLines2 } from './enrichedFlattenFinancialLines2';


export interface LignesFinancieres { 
    type?: LignesFinancieres.TypeEnum;
    lignes: Array<EnrichedFlattenFinancialLines2>;
}
export namespace LignesFinancieres {
    export type TypeEnum = 'lignes_financieres';
    export const TypeEnum = {
        LignesFinancieres: 'lignes_financieres' as TypeEnum
    };
}


