/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIError } from '../model/models';
import { DetailsPaiementResponse } from '../model/models';


import { financialDataV3Configuration }                                     from '../configuration';


export interface GetDetailsPaiementPourLigneFinanciereLignesIdAeDetailsPaiementGetRequestParams {
    idAe: number;
}


export interface DtailsPaiementServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: financialDataV3Configuration;

    /**
     * Récupére les détails de paiement associés à une ligne financière de type AE
     * 
* @param requestParameters
     */
    getDetailsPaiementPourLigneFinanciereLignesIdAeDetailsPaiementGet(requestParameters: GetDetailsPaiementPourLigneFinanciereLignesIdAeDetailsPaiementGetRequestParams, extraHttpRequestParams?: any): Observable<DetailsPaiementResponse>;

}
