/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { APIError } from '../model/aPIError';
// @ts-ignore
import { DetailsPaiementResponse } from '../model/detailsPaiementResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { financialDataV3Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    DtailsPaiementServiceInterface,
    GetDetailsPaiementPourLigneFinanciereLignesIdAeDetailsPaiementGetRequestParams
} from './dtailsPaiement.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class DtailsPaiementService extends BaseService implements DtailsPaiementServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: financialDataV3Configuration) {
        super(basePath, configuration);
    }

    /**
     * Récupére les détails de paiement associés à une ligne financière de type AE
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDetailsPaiementPourLigneFinanciereLignesIdAeDetailsPaiementGet(requestParameters: GetDetailsPaiementPourLigneFinanciereLignesIdAeDetailsPaiementGetRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<DetailsPaiementResponse>;
    public getDetailsPaiementPourLigneFinanciereLignesIdAeDetailsPaiementGet(requestParameters: GetDetailsPaiementPourLigneFinanciereLignesIdAeDetailsPaiementGetRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<DetailsPaiementResponse>>;
    public getDetailsPaiementPourLigneFinanciereLignesIdAeDetailsPaiementGet(requestParameters: GetDetailsPaiementPourLigneFinanciereLignesIdAeDetailsPaiementGetRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<DetailsPaiementResponse>>;
    public getDetailsPaiementPourLigneFinanciereLignesIdAeDetailsPaiementGet(requestParameters: GetDetailsPaiementPourLigneFinanciereLignesIdAeDetailsPaiementGetRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const idAe = requestParameters?.idAe;
        if (idAe === null || idAe === undefined) {
            throw new Error('Required parameter idAe was null or undefined when calling getDetailsPaiementPourLigneFinanciereLignesIdAeDetailsPaiementGet.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (OAuth2PasswordBearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('OAuth2PasswordBearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/lignes/${this.configuration.encodeParam({name: "idAe", value: idAe, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: undefined})}/details-paiement`;
        return this.httpClient.request<DetailsPaiementResponse>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
