/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIError } from '../model/models';


import { financialDataV3Configuration }                                     from '../configuration';


export interface HealthcheckHealthcheckGetRequestParams {
    colonnes?: string | null;
    page?: number;
    pageSize?: number;
    sortBy?: string | null;
    sortOrder?: 'asc' | 'desc' | null;
    search?: string | null;
    fieldsSearch?: string | null;
    sourceRegion?: string | null;
    dataSource?: string | null;
    source?: string | null;
    codeProgramme?: string | null;
    niveauGeo?: string | null;
    codeGeo?: string | null;
    refQpv?: '2015' | '2024' | null;
    codeQpv?: string | null;
    theme?: string | null;
    beneficiaireCode?: string | null;
    beneficiaireCategorieJuridiqueType?: string | null;
    annee?: string | null;
    centresCouts?: string | null;
    nEj?: string | null;
    domaineFonctionnel?: string | null;
    referentielProgrammation?: string | null;
    tags?: string | null;
    grouping?: string | null;
    grouped?: string | null;
}


export interface HealthcheckServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: financialDataV3Configuration;

    /**
     * Vérification de la disponibilité de l\&#39;API des lignes budgetaires
     * 
* @param requestParameters
     */
    healthcheckHealthcheckGet(requestParameters: HealthcheckHealthcheckGetRequestParams, extraHttpRequestParams?: any): Observable<any>;

}
