/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { InitializeSessionRequest } from '../model/models';


import { financialDataV3Configuration }                                     from '../configuration';


export interface CheckSessionImportSessionSessionTokenGetRequestParams {
    sessionToken: string;
}

export interface CoreHeadRouteImportUuidHeadRequestParams {
    uuid: string;
    tusResumable?: string;
}

export interface CoreOptionsRouteImportOptionsRequestParams {
    tusResumable?: string;
}

export interface CorePatchRouteImportUuidPatchRequestParams {
    uuid: string;
    contentLength: number;
    uploadOffset: number;
    postRequest?: boolean;
    uploadLength?: number;
    contentType?: string;
    tusResumable?: string;
}

export interface ExtensionCreationRouteImportPostRequestParams {
    uploadMetadata?: string;
    uploadLength?: number;
    uploadDeferLength?: number;
    uploadConcat?: string;
    tusResumable?: string;
}

export interface ExtensionCreationRouteImportPost0RequestParams {
    uploadMetadata?: string;
    uploadLength?: number;
    uploadDeferLength?: number;
    uploadConcat?: string;
    tusResumable?: string;
}

export interface ExtensionTerminationRouteImportUuidDeleteRequestParams {
    uuid: string;
    tusResumable?: string;
}

export interface InitializeSessionImportSessionInitializePostRequestParams {
    initializeSessionRequest: InitializeSessionRequest;
}


export interface ImportChorusServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: financialDataV3Configuration;

    /**
     * Vérifie si une requête d\&#39;import a été enregistrée dans le système.
     * 
* @param requestParameters
     */
    checkSessionImportSessionSessionTokenGet(requestParameters: CheckSessionImportSessionSessionTokenGetRequestParams, extraHttpRequestParams?: any): Observable<any>;

    /**
     * Core Head Route
     * 
* @param requestParameters
     */
    coreHeadRouteImportUuidHead(requestParameters: CoreHeadRouteImportUuidHeadRequestParams, extraHttpRequestParams?: any): Observable<any>;

    /**
     * Core Options Route
     * 
* @param requestParameters
     */
    coreOptionsRouteImportOptions(requestParameters: CoreOptionsRouteImportOptionsRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Core Patch Route
     * 
* @param requestParameters
     */
    corePatchRouteImportUuidPatch(requestParameters: CorePatchRouteImportUuidPatchRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Extension Creation Route
     * 
* @param requestParameters
     */
    extensionCreationRouteImportPost(requestParameters: ExtensionCreationRouteImportPostRequestParams, extraHttpRequestParams?: any): Observable<any>;

    /**
     * Extension Creation Route
     * 
* @param requestParameters
     */
    extensionCreationRouteImportPost_1(requestParameters: ExtensionCreationRouteImportPost0RequestParams, extraHttpRequestParams?: any): Observable<any>;

    /**
     * Extension Termination Route
     * 
* @param requestParameters
     */
    extensionTerminationRouteImportUuidDelete(requestParameters: ExtensionTerminationRouteImportUuidDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Initialise et persiste l\&#39;état d\&#39;une session d\&#39;upload avant l\&#39;envoi des fichiers.
     * 
* @param requestParameters
     */
    initializeSessionImportSessionInitializePost(requestParameters: InitializeSessionImportSessionInitializePostRequestParams, extraHttpRequestParams?: any): Observable<{ [key: string]: string | null; }>;

}
