/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIError } from '../model/models';
import { APISuccessListInt } from '../model/models';
import { DoExportResponse } from '../model/models';
import { ExportsResponse } from '../model/models';
import { LigneResponse } from '../model/models';
import { LignesResponse } from '../model/models';


import { financialDataV3Configuration }                                     from '../configuration';


export interface DoExportLignesExportPostRequestParams {
    format?: 'csv' | 'xlsx' | 'ods' | 'to-grist';
    colonnes?: string | null;
    page?: number;
    pageSize?: number;
    sortBy?: string | null;
    sortOrder?: 'asc' | 'desc' | null;
    search?: string | null;
    fieldsSearch?: string | null;
    sourceRegion?: string | null;
    dataSource?: string | null;
    source?: string | null;
    codeProgramme?: string | null;
    niveauGeo?: string | null;
    codeGeo?: string | null;
    refQpv?: '2015' | '2024' | null;
    codeQpv?: string | null;
    theme?: string | null;
    beneficiaireCode?: string | null;
    beneficiaireCategorieJuridiqueType?: string | null;
    annee?: string | null;
    centresCouts?: string | null;
    nEj?: string | null;
    domaineFonctionnel?: string | null;
    referentielProgrammation?: string | null;
    tags?: string | null;
    grouping?: string | null;
    grouped?: string | null;
}

export interface DownloadExportLignesDownloadUuidGetRequestParams {
    uuid: string;
}

export interface GetAnneesLignesAnneesGetRequestParams {
    colonnes?: string | null;
    page?: number;
    pageSize?: number;
    sortBy?: string | null;
    sortOrder?: 'asc' | 'desc' | null;
    search?: string | null;
    fieldsSearch?: string | null;
    sourceRegion?: string | null;
    dataSource?: string | null;
    source?: string | null;
}

export interface GetExportLignesExportUuidGetRequestParams {
    uuid: string;
}

export interface GetLignesFinancieresBySourceLignesIdGetRequestParams {
    id: number;
    colonnes?: string | null;
    page?: number;
    pageSize?: number;
    sortBy?: string | null;
    sortOrder?: 'asc' | 'desc' | null;
    search?: string | null;
    fieldsSearch?: string | null;
    sourceRegion?: string | null;
    dataSource?: string | null;
    source?: string | null;
}

export interface GetLignesFinancieresLignesGetRequestParams {
    forceNoCache?: boolean;
    colonnes?: string | null;
    page?: number;
    pageSize?: number;
    sortBy?: string | null;
    sortOrder?: 'asc' | 'desc' | null;
    search?: string | null;
    fieldsSearch?: string | null;
    sourceRegion?: string | null;
    dataSource?: string | null;
    source?: string | null;
    codeProgramme?: string | null;
    niveauGeo?: string | null;
    codeGeo?: string | null;
    refQpv?: '2015' | '2024' | null;
    codeQpv?: string | null;
    theme?: string | null;
    beneficiaireCode?: string | null;
    beneficiaireCategorieJuridiqueType?: string | null;
    annee?: string | null;
    centresCouts?: string | null;
    nEj?: string | null;
    domaineFonctionnel?: string | null;
    referentielProgrammation?: string | null;
    tags?: string | null;
    grouping?: string | null;
    grouped?: string | null;
}


export interface LignesFinancieresServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: financialDataV3Configuration;

    /**
     * Enregistre une tâche d\&#39;export des lignes financières
     * 
* @param requestParameters
     */
    doExportLignesExportPost(requestParameters: DoExportLignesExportPostRequestParams, extraHttpRequestParams?: any): Observable<DoExportResponse>;

    /**
     * Télécharge un export existant selon son id
     * 
* @param requestParameters
     */
    downloadExportLignesDownloadUuidGet(requestParameters: DownloadExportLignesDownloadUuidGetRequestParams, extraHttpRequestParams?: any): Observable<any>;

    /**
     * Recupère la plage des années pour lesquelles les données budgetaires courent.
     * 
* @param requestParameters
     */
    getAnneesLignesAnneesGet(requestParameters: GetAnneesLignesAnneesGetRequestParams, extraHttpRequestParams?: any): Observable<APISuccessListInt>;

    /**
     * Récupère les informations d\&#39;un export
     * 
* @param requestParameters
     */
    getExportLignesExportUuidGet(requestParameters: GetExportLignesExportUuidGetRequestParams, extraHttpRequestParams?: any): Observable<DoExportResponse>;

    /**
     * Récupére les infos budgetaires en fonction de son identifiant technique
     * 
* @param requestParameters
     */
    getLignesFinancieresBySourceLignesIdGet(requestParameters: GetLignesFinancieresBySourceLignesIdGetRequestParams, extraHttpRequestParams?: any): Observable<LigneResponse>;

    /**
     * Récupére les lignes financières, mécanisme de grouping pour récupérer les montants agrégés
     * 
* @param requestParameters
     */
    getLignesFinancieresLignesGet(requestParameters: GetLignesFinancieresLignesGetRequestParams, extraHttpRequestParams?: any): Observable<LignesResponse>;

    /**
     * Liste les tâches d\&#39;export des lignes financières
     * 
*/
    listExportsLignesExportsGet(extraHttpRequestParams?: any): Observable<ExportsResponse>;

}
