/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIError } from '../model/models';
import { APISuccessAnnotatedEnrichedFlattenFinancialLinesPydanticFromMarshmallowSchemaAnnotationTSchema } from '../model/models';
import { APISuccessListInt } from '../model/models';
import { APISuccessUnionLignesFinancieresGroupingsNoneType } from '../model/models';


import { financialDataV3Configuration }                                     from '../configuration';



export interface LignesFinanciresServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: financialDataV3Configuration;

    /**
     * Recupère la plage des années pour lesquelles les données budgetaires courent.
     * 
     * @param sourceRegion 
     * @param dataSource 
     * @param source 
     * @param colonnes 
     * @param page 
     * @param pageSize 
     * @param sortBy 
     * @param sortOrder 
     * @param search 
     * @param fieldsSearch 
     */
    getAnneesLignesAnneesGet(sourceRegion?: string, dataSource?: string, source?: string, colonnes?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: 'asc' | 'desc', search?: string, fieldsSearch?: string, extraHttpRequestParams?: any): Observable<APISuccessListInt>;

    /**
     * Récupére les infos budgetaires en fonction de son identifiant technique
     * 
     * @param id 
     * @param sourceRegion 
     * @param dataSource 
     * @param source 
     * @param colonnes 
     * @param page 
     * @param pageSize 
     * @param sortBy 
     * @param sortOrder 
     * @param search 
     * @param fieldsSearch 
     */
    getLignesFinancieresBySourceLignesIdGet(id: number, sourceRegion?: string, dataSource?: string, source?: string, colonnes?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: 'asc' | 'desc', search?: string, fieldsSearch?: string, extraHttpRequestParams?: any): Observable<APISuccessAnnotatedEnrichedFlattenFinancialLinesPydanticFromMarshmallowSchemaAnnotationTSchema>;

    /**
     * Récupére les lignes financières, mécanisme de grouping pour récupérer les montants agrégés
     * 
     * @param sourceRegion 
     * @param dataSource 
     * @param source 
     * @param nEj 
     * @param codeProgramme 
     * @param niveauGeo 
     * @param codeGeo 
     * @param refQpv 
     * @param codeQpv 
     * @param theme 
     * @param beneficiaireCode Siret du bénéficiaire
     * @param beneficiaireCategorieJuridiqueType Type de la catégorie juridique du bénéficiaire
     * @param annee 
     * @param centresCouts 
     * @param domaineFonctionnel 
     * @param referentielProgrammation 
     * @param tags 
     * @param grouping 
     * @param grouped 
     * @param colonnes 
     * @param page 
     * @param pageSize 
     * @param sortBy 
     * @param sortOrder 
     * @param search 
     * @param fieldsSearch 
     */
    getLignesFinancieresLignesGet(sourceRegion?: string, dataSource?: string, source?: string, nEj?: string, codeProgramme?: string, niveauGeo?: string, codeGeo?: string, refQpv?: 2015 | 2024, codeQpv?: string, theme?: string, beneficiaireCode?: string, beneficiaireCategorieJuridiqueType?: string, annee?: string, centresCouts?: string, domaineFonctionnel?: string, referentielProgrammation?: string, tags?: string, grouping?: string, grouped?: string, colonnes?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: 'asc' | 'desc', search?: string, fieldsSearch?: string, extraHttpRequestParams?: any): Observable<APISuccessUnionLignesFinancieresGroupingsNoneType>;

}
