/**
 * API V3 - Data Etat - Budget
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIError } from '../model/models';
import { APISuccessListColonne } from '../model/models';


import { financialDataV3Configuration }                                     from '../configuration';



export interface ListeDesColonnesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: financialDataV3Configuration;

    /**
     * Liste des colonnes possibles pour le grouping
     * 
     */
    getColonnesGroupingColonnesGroupingGet(extraHttpRequestParams?: any): Observable<APISuccessListColonne>;

    /**
     * Liste des colonnes possibles pour le tableau
     * 
     */
    getColonnesTableauColonnesTableauGet(extraHttpRequestParams?: any): Observable<APISuccessListColonne>;

}
