/**
 * API V3 - Data Etat - Référentiels
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIError } from '../model/models';
import { CentreCoutsResponse } from '../model/models';


import { referentielsV3Configuration }                                     from '../configuration';


export interface GetByCodeCentreCoutsCodeGetRequestParams {
    code: string;
    colonnes?: string | null;
    page?: number;
    pageSize?: number;
    sortBy?: string | null;
    sortOrder?: 'asc' | 'desc' | null;
    search?: string | null;
    fieldsSearch?: string | null;
}

export interface ListAllCentreCoutsGetRequestParams {
    colonnes?: string | null;
    page?: number;
    pageSize?: number;
    sortBy?: string | null;
    sortOrder?: 'asc' | 'desc' | null;
    search?: string | null;
    fieldsSearch?: string | null;
}


export interface CentreCoutsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: referentielsV3Configuration;

    /**
     * Get centre-couts by code
     * 
* @param requestParameters
     */
    getByCodeCentreCoutsCodeGet(requestParameters: GetByCodeCentreCoutsCodeGetRequestParams, extraHttpRequestParams?: any): Observable<CentreCoutsResponse>;

    /**
     * Liste de tous les centre-couts
     * 
* @param requestParameters
     */
    listAllCentreCoutsGet(requestParameters: ListAllCentreCoutsGetRequestParams, extraHttpRequestParams?: any): Observable<CentreCoutsResponse>;

}
