/**
 * API V3 - Data Etat - Référentiels
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIError } from '../model/models';
import { APISuccess } from '../model/models';


import { referentielsV3Configuration }                                     from '../configuration';



export interface HealthcheckServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: referentielsV3Configuration;

    /**
     * Healthcheck
     * 
*/
    healthcheckHealthcheckGet(extraHttpRequestParams?: any): Observable<APISuccess>;

}
