/**
 * API V3 - Data Etat - Référentiels
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIError } from '../model/models';


import { referentielsV3Configuration }                                     from '../configuration';



export interface ProgrammesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: referentielsV3Configuration;

    /**
     * Get programmes by code
     * 
     * @param code 
     * @param colonnes 
     * @param page 
     * @param pageSize 
     * @param sortBy 
     * @param sortOrder 
     * @param search 
     * @param fieldsSearch 
     */
    getByCodeProgrammesCodeGet(code: string, colonnes?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: 'asc' | 'desc', search?: string, fieldsSearch?: string, extraHttpRequestParams?: any): Observable<any>;

    /**
     * Liste de tous les programmes
     * 
     * @param colonnes 
     * @param page 
     * @param pageSize 
     * @param sortBy 
     * @param sortOrder 
     * @param search 
     * @param fieldsSearch 
     */
    listAllProgrammesGet(colonnes?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: 'asc' | 'desc', search?: string, fieldsSearch?: string, extraHttpRequestParams?: any): Observable<any>;

}
