/**
 * API V3 - Data Etat - Référentiels
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIError } from '../model/models';
import { ProgrammeResponse } from '../model/models';


import { referentielsV3Configuration }                                     from '../configuration';


export interface GetByCodeProgrammesCodeGetRequestParams {
    code: string;
    colonnes?: string | null;
    page?: number;
    pageSize?: number;
    sortBy?: string | null;
    sortOrder?: 'asc' | 'desc' | null;
    search?: string | null;
    fieldsSearch?: string | null;
}

export interface ListAllProgrammesGetRequestParams {
    colonnes?: string | null;
    page?: number;
    pageSize?: number;
    sortBy?: string | null;
    sortOrder?: 'asc' | 'desc' | null;
    search?: string | null;
    fieldsSearch?: string | null;
}


export interface ProgrammesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: referentielsV3Configuration;

    /**
     * Get programmes by code
     * 
* @param requestParameters
     */
    getByCodeProgrammesCodeGet(requestParameters: GetByCodeProgrammesCodeGetRequestParams, extraHttpRequestParams?: any): Observable<ProgrammeResponse>;

    /**
     * Liste de tous les programmes
     * 
* @param requestParameters
     */
    listAllProgrammesGet(requestParameters: ListAllProgrammesGetRequestParams, extraHttpRequestParams?: any): Observable<ProgrammeResponse>;

}
