/**
 * API V3 - Data Etat - Référentiels
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIError } from '../model/models';
import { QpvResponse } from '../model/models';


import { referentielsV3Configuration }                                     from '../configuration';



export interface QpvServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: referentielsV3Configuration;

    /**
     * Find all QPV by annee
     * 
     * @param annee 
     * @param colonnes 
     * @param page 
     * @param pageSize 
     * @param sortBy 
     * @param sortOrder 
     * @param search 
     * @param fieldsSearch 
     */
    findAllByAnneeDecoupageQpvDecoupageAnneeGet(annee: string, colonnes?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: 'asc' | 'desc', search?: string, fieldsSearch?: string, extraHttpRequestParams?: any): Observable<QpvResponse>;

    /**
     * Get qpv by code
     * 
     * @param code 
     * @param colonnes 
     * @param page 
     * @param pageSize 
     * @param sortBy 
     * @param sortOrder 
     * @param search 
     * @param fieldsSearch 
     */
    getByCodeQpvCodeGet(code: string, colonnes?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: 'asc' | 'desc', search?: string, fieldsSearch?: string, extraHttpRequestParams?: any): Observable<QpvResponse>;

    /**
     * Liste de tous les qpv
     * 
     * @param colonnes 
     * @param page 
     * @param pageSize 
     * @param sortBy 
     * @param sortOrder 
     * @param search 
     * @param fieldsSearch 
     */
    listAllQpvGet(colonnes?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: 'asc' | 'desc', search?: string, fieldsSearch?: string, extraHttpRequestParams?: any): Observable<QpvResponse>;

}
