/**
 * API V3 - Data Etat - Référentiels
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIError } from '../model/models';
import { QpvResponse } from '../model/models';


import { referentielsV3Configuration }                                     from '../configuration';


export interface FindAllByAnneeDecoupageQpvDecoupageAnneeGetRequestParams {
    annee: string;
    colonnes?: string | null;
    page?: number;
    pageSize?: number;
    sortBy?: string | null;
    sortOrder?: 'asc' | 'desc' | null;
    search?: string | null;
    fieldsSearch?: string | null;
}

export interface GetByCodeQpvCodeGetRequestParams {
    code: string;
    colonnes?: string | null;
    page?: number;
    pageSize?: number;
    sortBy?: string | null;
    sortOrder?: 'asc' | 'desc' | null;
    search?: string | null;
    fieldsSearch?: string | null;
}

export interface ListAllQpvGetRequestParams {
    colonnes?: string | null;
    page?: number;
    pageSize?: number;
    sortBy?: string | null;
    sortOrder?: 'asc' | 'desc' | null;
    search?: string | null;
    fieldsSearch?: string | null;
}


export interface QpvServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: referentielsV3Configuration;

    /**
     * Find all QPV by annee
     * 
* @param requestParameters
     */
    findAllByAnneeDecoupageQpvDecoupageAnneeGet(requestParameters: FindAllByAnneeDecoupageQpvDecoupageAnneeGetRequestParams, extraHttpRequestParams?: any): Observable<QpvResponse>;

    /**
     * Get qpv by code
     * 
* @param requestParameters
     */
    getByCodeQpvCodeGet(requestParameters: GetByCodeQpvCodeGetRequestParams, extraHttpRequestParams?: any): Observable<QpvResponse>;

    /**
     * Liste de tous les qpv
     * 
* @param requestParameters
     */
    listAllQpvGet(requestParameters: ListAllQpvGetRequestParams, extraHttpRequestParams?: any): Observable<QpvResponse>;

}
