/**
 * API V3 - Data Etat - Data QPV
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface APIError { 
    code: number;
    success?: boolean | null;
    timestamp?: string;
    message?: string | null;
    detail?: string | null;
}

