/**
 * API V3 - Data Etat - Data QPV
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginationMeta } from './paginationMeta';
import { Colonne } from './colonne';


export interface APISuccessListColonne { 
    code: number;
    success?: boolean | null;
    timestamp?: string;
    message?: string | null;
    data?: Array<Colonne> | null;
    pagination: PaginationMeta | null;
}

