/**
 * API V3 - Data Etat - Data QPV
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Colonne { 
    code?: string | null;
    label?: string | null;
    'default'?: boolean;
    concatenate?: string | null;
}

