/**
 * API V3 - Data Etat - Data QPV
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChartData } from './chartData';


export interface DashboardData { 
    total_financements?: number;
    total_actions?: number;
    total_porteurs?: number;
    pie_chart_themes?: ChartData;
    pie_chart_types_porteurs?: ChartData;
    line_chart_annees?: ChartData;
}

