/**
 * API V3 - Data Etat - Data QPV
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnrichedFlattenFinancialLinesDataQPV1 } from './enrichedFlattenFinancialLinesDataQPV1';


export interface LignesFinancieres { 
    lignes: Array<EnrichedFlattenFinancialLinesDataQPV1>;
}

