/**
 * API V3 - Data Etat - Data QPV
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QpvData } from './qpvData';


export interface MapData { 
    data?: Array<QpvData>;
}

