/**
 * API V3 - Data Etat - Référentiels
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CentreCouts1 } from './centreCouts1';


export interface CentreCoutsResponse { 
    code: number;
    success?: boolean | null;
    timestamp?: string;
    message?: string | null;
    data?: Array<CentreCouts1> | null;
    current_page?: number | null;
    has_next?: boolean | null;
}

