/**
 * API V3 - Data Etat - Référentiels
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * dict() -> new empty dictionary dict(mapping) -> new dictionary initialized from a mapping object\'s     (key, value) pairs dict(iterable) -> new dictionary initialized as if via:     d = {}     for k, v in iterable:         d[k] = v dict(**kwargs) -> new dictionary initialized with the name=value pairs     in the keyword argument list.  For example:  dict(one=1, two=2)
 */
export interface Qpv { 
    code?: string | null;
    label?: string | null;
    label_commune?: string | null;
    annee_decoupage?: number | null;
    geom?: string | null;
    centroid?: string | null;
}

