/**
 * API V3 - Data Etat - Référentiels
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Qpv1 } from './qpv1';


export interface QpvResponse { 
    code: number;
    success?: boolean | null;
    timestamp?: string;
    message?: string | null;
    data?: Array<Qpv1> | null;
    current_page?: number | null;
    has_next?: boolean | null;
}

