/**
 * API V3 - Data Etat - API externes
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AcheminementPostal { 
    l1: string;
    l2: string;
    l3: string;
    l4: string;
    l5: string;
    l6: string | null;
    l7: string;
}

