/**
 * API V3 - Data Etat - API externes
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AcheminementPostal } from './acheminementPostal';


export interface Adresse { 
    code_commune: string | null;
    code_postal: string | null;
    code_cedex: string | null;
    libelle_commune: string | null;
    acheminement_postal: AcheminementPostal;
}

