/**
 * API V3 - Data Etat - API externes
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CodeErreur } from './codeErreur';


export interface ApiExterneError { 
    code: CodeErreur;
    message: string;
    remote_errors: Array<any>;
}
export namespace ApiExterneError {
}


