/**
 * API V3 - Data Etat - API externes
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Qualification } from './qualification';


export interface CertificationRge { 
    url: string;
    nom_certificat: string;
    domaine: string;
    meta_domaine: string;
    qualification: Qualification;
    organisme: string;
    date_attribution: string;
    date_expiration: string;
}

