/**
 * API V3 - Data Etat - API externes
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CodeErreur = 'UNKNOWN' | 'REMOTE_CALL_FAILED' | 'LIMIT_HIT' | 'INVALID_TOKEN' | 'UNAUTHORIZED_ON_DEMARCHE' | 'DEMARCHE_NOT_FOUND' | 'DATA_SUBVENTION_NOT_AN_ASSOCIATION';

export const CodeErreur = {

    Unknown: 'UNKNOWN' as CodeErreur,

    RemoteCallFailed: 'REMOTE_CALL_FAILED' as CodeErreur,

    LimitHit: 'LIMIT_HIT' as CodeErreur,

    InvalidToken: 'INVALID_TOKEN' as CodeErreur,

    UnauthorizedOnDemarche: 'UNAUTHORIZED_ON_DEMARCHE' as CodeErreur,

    DemarcheNotFound: 'DEMARCHE_NOT_FOUND' as CodeErreur,

    DataSubventionNotAnAssociation: 'DATA_SUBVENTION_NOT_AN_ASSOCIATION' as CodeErreur
};

