/**
 * API V3 - Data Etat - API externes
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Adresse } from './adresse';
import { UniteLegale } from './uniteLegale';
import { TrancheEffectifSalarie } from './trancheEffectifSalarie';
import { ActivitePrincipale } from './activitePrincipale';


export interface DonneesEtablissement { 
    siret: string;
    activite_principale: ActivitePrincipale;
    tranche_effectif_salarie: TrancheEffectifSalarie;
    unite_legale: UniteLegale;
    date_creation: number | null;
    adresse: Adresse;
    adresse_postale_legere: string;
}

