/**
 * API V3 - Data Etat - API externes
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CertificationRgeHolder } from './certificationRgeHolder';
import { NumeroTvaHolder } from './numeroTvaHolder';
import { ChiffreDaffairesHolder } from './chiffreDaffairesHolder';
import { CertificationQualibat } from './certificationQualibat';
import { DonneesEtablissement } from './donneesEtablissement';


export interface InfoApiEntreprise { 
    donnees_etablissement: DonneesEtablissement;
    tva_indispo: boolean;
    tva: NumeroTvaHolder | null;
    chiffre_d_affaires_indispo: boolean;
    chiffre_d_affaires: Array<ChiffreDaffairesHolder>;
    certifications_rge_indispo: boolean;
    certifications_rge: Array<CertificationRgeHolder>;
    certification_qualibat_indispo: boolean;
    certification_qualibat: CertificationQualibat | null;
}

