/**
 * API V3 - Data Etat - API externes
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Subvention } from './subvention';
import { RepresentantLegal } from './representantLegal';


export interface InfoApiSubvention { 
    subventions: Array<Subvention>;
    contacts: Array<RepresentantLegal>;
}

