/**
 * API V3 - Data Etat - API externes
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonnePhysiqueAttributs { 
    pseudonyme?: string | null;
    prenom_usuel?: string | null;
    prenom_1?: string | null;
    prenom_2?: string | null;
    prenom_3?: string | null;
    prenom_4?: string | null;
    nom_usage?: string | null;
    nom_naissance?: string | null;
    _sexe?: string | null;
}

