/**
 * API V3 - Data Etat - API externes
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrancheEffectifSalarie { 
    code: string | null;
    intitule: string | null;
    date_reference: string | null;
    de: number | null;
    a: number | null;
}

