/**
 * API V3 - Data Etat - Data QPV
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIError } from '../model/models';
import { DashboardResponse } from '../model/models';


import { dataQpvV3Configuration }                                     from '../configuration';


export interface GetDashboardDashboardsGetRequestParams {
    sourceRegion?: string | null;
    dataSource?: string | null;
    source?: string | null;
    codeProgramme?: string | null;
    notCodeProgramme?: string | null;
    annee?: string | null;
    niveauGeo?: string | null;
    codeGeo?: string | null;
    refQpv?: '2015' | '2024' | null;
    codeQpv?: string | null;
    theme?: string | null;
    beneficiaireCode?: string | null;
    beneficiaireCategorieJuridiqueType?: string | null;
    centresCouts?: string | null;
    colonnes?: string | null;
    page?: number;
    pageSize?: number;
    sortBy?: string | null;
    sortOrder?: 'asc' | 'desc' | null;
    search?: string | null;
    fieldsSearch?: string | null;
}


export interface DashboardsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: dataQpvV3Configuration;

    /**
     * Récupére les lignes QPV agrégées pour les graphiques
     * 
* @param requestParameters
     */
    getDashboardDashboardsGet(requestParameters: GetDashboardDashboardsGetRequestParams, extraHttpRequestParams?: any): Observable<DashboardResponse>;

}
