/**
 * API V3 - Data Etat - Data QPV
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIError } from '../model/models';
import { APISuccessListInt } from '../model/models';
import { LignesResponse } from '../model/models';


import { dataQpvV3Configuration }                                     from '../configuration';



export interface LignesFinancieresServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: dataQpvV3Configuration;

    /**
     * Recupère la plage des années pour lesquelles les données QPV courent.
     * 
     * @param sourceRegion 
     * @param dataSource 
     * @param source 
     * @param colonnes 
     * @param page 
     * @param pageSize 
     * @param sortBy 
     * @param sortOrder 
     * @param search 
     * @param fieldsSearch 
     */
    getAnneesLignesAnneesGet(sourceRegion?: string, dataSource?: string, source?: string, colonnes?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: 'asc' | 'desc', search?: string, fieldsSearch?: string, extraHttpRequestParams?: any): Observable<APISuccessListInt>;

    /**
     * Récupére les lignes QPV
     * 
     * @param sourceRegion 
     * @param dataSource 
     * @param source 
     * @param codeProgramme 
     * @param notCodeProgramme 
     * @param annee 
     * @param niveauGeo 
     * @param codeGeo 
     * @param refQpv 
     * @param codeQpv 
     * @param theme 
     * @param beneficiaireCode Siret du bénéficiaire
     * @param beneficiaireCategorieJuridiqueType Type de la catégorie juridique du bénéficiaire
     * @param centresCouts 
     * @param colonnes 
     * @param page 
     * @param pageSize 
     * @param sortBy 
     * @param sortOrder 
     * @param search 
     * @param fieldsSearch 
     */
    getLignesFinancieresLignesGet(sourceRegion?: string, dataSource?: string, source?: string, codeProgramme?: string, notCodeProgramme?: string, annee?: string, niveauGeo?: string, codeGeo?: string, refQpv?: '2015' | '2024', codeQpv?: string, theme?: string, beneficiaireCode?: string, beneficiaireCategorieJuridiqueType?: string, centresCouts?: string, colonnes?: string, page?: number, pageSize?: number, sortBy?: string, sortOrder?: 'asc' | 'desc', search?: string, fieldsSearch?: string, extraHttpRequestParams?: any): Observable<LignesResponse>;

}
