/**
 * API V3 - Data Etat - Data QPV
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { APIError } from '../model/aPIError';
// @ts-ignore
import { APISuccessListInt } from '../model/aPISuccessListInt';
// @ts-ignore
import { LignesResponse } from '../model/lignesResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { dataQpvV3Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    LignesFinancieresServiceInterface,
    GetAnneesLignesAnneesGetRequestParams,
    GetLignesFinancieresLignesGetRequestParams
} from './lignesFinancieres.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class LignesFinancieresService extends BaseService implements LignesFinancieresServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: dataQpvV3Configuration) {
        super(basePath, configuration);
    }

    /**
     * Recupère la plage des années pour lesquelles les données QPV courent.
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAnneesLignesAnneesGet(requestParameters?: GetAnneesLignesAnneesGetRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<APISuccessListInt>;
    public getAnneesLignesAnneesGet(requestParameters?: GetAnneesLignesAnneesGetRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<APISuccessListInt>>;
    public getAnneesLignesAnneesGet(requestParameters?: GetAnneesLignesAnneesGetRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<APISuccessListInt>>;
    public getAnneesLignesAnneesGet(requestParameters?: GetAnneesLignesAnneesGetRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const sourceRegion = requestParameters?.sourceRegion;
        const dataSource = requestParameters?.dataSource;
        const source = requestParameters?.source;
        const colonnes = requestParameters?.colonnes;
        const page = requestParameters?.page;
        const pageSize = requestParameters?.pageSize;
        const sortBy = requestParameters?.sortBy;
        const sortOrder = requestParameters?.sortOrder;
        const search = requestParameters?.search;
        const fieldsSearch = requestParameters?.fieldsSearch;

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sourceRegion, 'source_region');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>dataSource, 'data_source');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>source, 'source');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>colonnes, 'colonnes');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'page_size');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sortBy, 'sort_by');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sortOrder, 'sort_order');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>search, 'search');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>fieldsSearch, 'fields_search');

        let localVarHeaders = this.defaultHeaders;

        // authentication (OAuth2PasswordBearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('OAuth2PasswordBearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/lignes/annees`;
        return this.httpClient.request<APISuccessListInt>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Récupére les lignes QPV
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getLignesFinancieresLignesGet(requestParameters?: GetLignesFinancieresLignesGetRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<LignesResponse>;
    public getLignesFinancieresLignesGet(requestParameters?: GetLignesFinancieresLignesGetRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<LignesResponse>>;
    public getLignesFinancieresLignesGet(requestParameters?: GetLignesFinancieresLignesGetRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<LignesResponse>>;
    public getLignesFinancieresLignesGet(requestParameters?: GetLignesFinancieresLignesGetRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const sourceRegion = requestParameters?.sourceRegion;
        const dataSource = requestParameters?.dataSource;
        const source = requestParameters?.source;
        const codeProgramme = requestParameters?.codeProgramme;
        const notCodeProgramme = requestParameters?.notCodeProgramme;
        const annee = requestParameters?.annee;
        const niveauGeo = requestParameters?.niveauGeo;
        const codeGeo = requestParameters?.codeGeo;
        const refQpv = requestParameters?.refQpv;
        const codeQpv = requestParameters?.codeQpv;
        const theme = requestParameters?.theme;
        const beneficiaireCode = requestParameters?.beneficiaireCode;
        const beneficiaireCategorieJuridiqueType = requestParameters?.beneficiaireCategorieJuridiqueType;
        const centresCouts = requestParameters?.centresCouts;
        const colonnes = requestParameters?.colonnes;
        const page = requestParameters?.page;
        const pageSize = requestParameters?.pageSize;
        const sortBy = requestParameters?.sortBy;
        const sortOrder = requestParameters?.sortOrder;
        const search = requestParameters?.search;
        const fieldsSearch = requestParameters?.fieldsSearch;

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sourceRegion, 'source_region');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>dataSource, 'data_source');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>source, 'source');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>codeProgramme, 'code_programme');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>notCodeProgramme, 'not_code_programme');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>annee, 'annee');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>niveauGeo, 'niveau_geo');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>codeGeo, 'code_geo');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>refQpv, 'ref_qpv');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>codeQpv, 'code_qpv');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>theme, 'theme');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>beneficiaireCode, 'beneficiaire_code');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>beneficiaireCategorieJuridiqueType, 'beneficiaire_categorieJuridique_type');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>centresCouts, 'centres_couts');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>colonnes, 'colonnes');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'page_size');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sortBy, 'sort_by');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sortOrder, 'sort_order');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>search, 'search');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>fieldsSearch, 'fields_search');

        let localVarHeaders = this.defaultHeaders;

        // authentication (OAuth2PasswordBearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('OAuth2PasswordBearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/lignes`;
        return this.httpClient.request<LignesResponse>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
