/**
 * API V3 - Data Etat - Data QPV
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIError } from '../model/models';
import { APISuccessListColonne } from '../model/models';


import { dataQpvV3Configuration }                                     from '../configuration';



export interface ListeDesColonnesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: dataQpvV3Configuration;

    /**
     * Liste des colonnes à utiliser pour la recherche et le tableau
     * 
*/
    getColonnesTableauColonnesTableauGet(extraHttpRequestParams?: any): Observable<APISuccessListColonne>;

}
