server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    error_log /dev/stdout info;

    # Keep the CSP nonce dynamic for each HTML response.
    sub_filter_once off;
    sub_filter_types text/html;
    sub_filter '__CSP_NONCE__' '$request_id';

    add_header_inherit merge;
    add_header Content-Security-Policy "default-src 'none'; base-uri 'self'; frame-ancestors 'none'; frame-src 'none'; connect-src 'self' https://*.dataregion.fr https://*.databretagne.fr https://geo.api.gouv.fr; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob:; script-src 'self' https://*.dataregion.fr https://*.databretagne.fr; style-src 'self' 'nonce-$request_id' https://fonts.googleapis.com" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-XSS-Protection "1; mode=block" always;

    location = / {
        try_files /index.html =404;
    }

    location = /index.html {
        include /etc/nginx/no-cache.conf;
        try_files /index.html =404;
    }

    location = /assets/settings.json {
        include /etc/nginx/no-cache.conf;
        try_files /assets/settings.json =404;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        index index.html index.htm;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
