/**
 * API Data transform
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GristDataModel } from '../model/models';


import { budgetConfiguration }                                     from '../configuration';



export interface BudgetToGristServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: budgetConfiguration;

    /**
     * Récupère les données passé dans le body et les injectes dans le grist
     * 
     * @param payload 
     */
    postBugdetToGrist(payload: GristDataModel, extraHttpRequestParams?: any): Observable<{}>;

}
