/**
 * API V3 - Administration
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { APIError } from '../model/models';
import { APISuccessListUserSearchResponse } from '../model/models';
import { APISuccessPreferenceResponse } from '../model/models';
import { APISuccessPreferencesListResponse } from '../model/models';
import { APISuccessStr } from '../model/models';
import { PreferenceCreateRequest } from '../model/models';
import { PreferenceUpdateRequest } from '../model/models';


import { administrationV3Configuration }                                     from '../configuration';


export interface CreatePreferenceUsersPreferencesPostRequestParams {
    preferenceCreateRequest: PreferenceCreateRequest;
}

export interface DeletePreferenceUsersPreferencesUuidDeleteRequestParams {
    uuid: string;
}

export interface GetPreferenceUsersPreferencesUuidGetRequestParams {
    uuid: string;
}

export interface SearchUsersUsersPreferencesSearchUserGetRequestParams {
    username: string;
}

export interface UpdatePreferenceUsersPreferencesUuidPostRequestParams {
    uuid: string;
    preferenceUpdateRequest: PreferenceUpdateRequest;
}


export interface PrfrencesUtilisateurServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: administrationV3Configuration;

    /**
     * Créer une préférence utilisateur
     * Crée une nouvelle préférence pour l\&#39;utilisateur connecté avec possibilité de partage
* @param requestParameters
     */
    createPreferenceUsersPreferencesPost(requestParameters: CreatePreferenceUsersPreferencesPostRequestParams, extraHttpRequestParams?: any): Observable<APISuccessPreferenceResponse>;

    /**
     * Supprimer une préférence
     * Supprime définitivement une préférence
* @param requestParameters
     */
    deletePreferenceUsersPreferencesUuidDelete(requestParameters: DeletePreferenceUsersPreferencesUuidDeleteRequestParams, extraHttpRequestParams?: any): Observable<APISuccessStr>;

    /**
     * Récupérer une préférence par UUID
     * Récupère une préférence spécifique et incrémente son compteur d\&#39;utilisation
* @param requestParameters
     */
    getPreferenceUsersPreferencesUuidGet(requestParameters: GetPreferenceUsersPreferencesUuidGetRequestParams, extraHttpRequestParams?: any): Observable<APISuccessPreferenceResponse>;

    /**
     * Lister les préférences de l\&#39;utilisateur
     * Récupère toutes les préférences créées par l\&#39;utilisateur et celles partagées avec lui
*/
    listPreferencesUsersPreferencesGet(extraHttpRequestParams?: any): Observable<APISuccessPreferencesListResponse>;

    /**
     * Rechercher des utilisateurs Keycloak
     * Recherche des utilisateurs par nom d\&#39;utilisateur ou email pour le partage de préférences
* @param requestParameters
     */
    searchUsersUsersPreferencesSearchUserGet(requestParameters: SearchUsersUsersPreferencesSearchUserGetRequestParams, extraHttpRequestParams?: any): Observable<APISuccessListUserSearchResponse>;

    /**
     * Mettre à jour une préférence
     * Met à jour une préférence existante (nom, filtres, options, partages)
* @param requestParameters
     */
    updatePreferenceUsersPreferencesUuidPost(requestParameters: UpdatePreferenceUsersPreferencesUuidPostRequestParams, extraHttpRequestParams?: any): Observable<APISuccessPreferenceResponse>;

}
