/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AcheminementPostal } from './acheminementPostal';


export interface Adresse { 
    acheminement_postal: AcheminementPostal;
    code_cedex?: string;
    code_commune?: string;
    code_postal?: string;
    libelle_commune?: string;
}

