/**
 * API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonnePhysiqueAttributs { 
    _sexe?: string;
    nom_naissance?: string;
    nom_usage?: string;
    prenom_1?: string;
    prenom_2?: string;
    prenom_3?: string;
    prenom_4?: string;
    prenom_usuel?: string;
    pseudonyme?: string;
}

