/**
 * API Data transform
 * Api de d\'accès aux données financières de l\'état <br /><strong>C\'est une API dediée à l\'outil interne de consultation budget. utilisez pas cette API pour intégrer nos données à votre système.</strong>
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TagsSchema } from './tagsSchema';


export interface EnrichedFlattenFinancialLinesSchema { 
    annee?: number;
    beneficiaire_categorieJuridique_type?: string;
    beneficiaire_code?: string;
    beneficiaire_commune_arrondissement_code?: string;
    beneficiaire_commune_arrondissement_label?: string;
    beneficiaire_commune_code?: string;
    beneficiaire_commune_codeCrte?: string;
    beneficiaire_commune_codeDepartement?: string;
    beneficiaire_commune_codeEpci?: string;
    beneficiaire_commune_codeRegion?: string;
    beneficiaire_commune_label?: string;
    beneficiaire_commune_labelCrte?: string;
    beneficiaire_commune_labelDepartement?: string;
    beneficiaire_commune_labelEpci?: string;
    beneficiaire_commune_labelRegion?: string;
    beneficiaire_denomination?: string;
    beneficiaire_qpv24_code?: string;
    beneficiaire_qpv24_label?: string;
    beneficiaire_qpv_code?: string;
    beneficiaire_qpv_label?: string;
    centreCouts_code?: string;
    centreCouts_description?: string;
    centreCouts_label?: string;
    compte_budgetaire?: string;
    contrat_etat_region?: string;
    created_at?: string;
    data_source?: string;
    dateDeCreation?: string;
    dateDeDernierPaiement?: string;
    domaineFonctionnel_code?: string;
    domaineFonctionnel_label?: string;
    groupeMarchandise_code?: string;
    groupeMarchandise_label?: string;
    id?: number;
    localisationInterministerielle_code?: string;
    localisationInterministerielle_codeDepartement?: string;
    localisationInterministerielle_commune_arrondissement_code?: string;
    localisationInterministerielle_commune_arrondissement_label?: string;
    localisationInterministerielle_commune_code?: string;
    localisationInterministerielle_commune_codeCrte?: string;
    localisationInterministerielle_commune_codeDepartement?: string;
    localisationInterministerielle_commune_codeEpci?: string;
    localisationInterministerielle_commune_codeRegion?: string;
    localisationInterministerielle_commune_label?: string;
    localisationInterministerielle_commune_labelCrte?: string;
    localisationInterministerielle_commune_labelDepartement?: string;
    localisationInterministerielle_commune_labelEpci?: string;
    localisationInterministerielle_commune_labelRegion?: string;
    localisationInterministerielle_label?: string;
    montant_ae?: number;
    montant_cp?: number;
    n_ej?: string;
    n_poste_ej?: number;
    programme_code?: string;
    programme_label?: string;
    programme_theme?: string;
    referentielProgrammation_code?: string;
    referentielProgrammation_label?: string;
    source?: EnrichedFlattenFinancialLinesSchema.SourceEnum;
    source_region?: string;
    tags?: Array<TagsSchema>;
    updated_at?: string;
}
export namespace EnrichedFlattenFinancialLinesSchema {
    export type SourceEnum = 'FINANCIAL_DATA_AE' | 'FINANCIAL_DATA_CP' | 'FRANCE_RELANCE' | 'FRANCE_2030' | 'ADEME' | 'REFERENTIEL';
    export const SourceEnum = {
        FinancialDataAe: 'FINANCIAL_DATA_AE' as SourceEnum,
        FinancialDataCp: 'FINANCIAL_DATA_CP' as SourceEnum,
        FranceRelance: 'FRANCE_RELANCE' as SourceEnum,
        France2030: 'FRANCE_2030' as SourceEnum,
        Ademe: 'ADEME' as SourceEnum,
        Referentiel: 'REFERENTIEL' as SourceEnum
    };
}


