/**
 * API Data transform
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GristDataModel { 
    /**
     * Liste d\'objets sous forme clé valeur. La clé correspond à la colonne de grist.
     */
    data: Array<object>;
}

