/**
 * API Data transform
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Pagination } from './pagination';
import { EnrichedFlattenFinancialLinesSchema } from './enrichedFlattenFinancialLinesSchema';


export interface PaginatedBudgetLines { 
    items?: Array<EnrichedFlattenFinancialLinesSchema>;
    pageInfo?: Pagination;
}

