/**
 * API Data transform
 * Api de d\'accès aux données financières de l\'état <br /><strong>C\'est une API dediée à l\'outil interne de consultation budget. utilisez pas cette API pour intégrer nos données à votre système.</strong>
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TagsSchema { 
    description?: string;
    display_name: string;
    type: string;
    value?: string;
}

