/**
 * API Data transform
 * API de gestion des données financières
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TagsSchema { 
    description?: string;
    display_name: string;
    type: string;
    value?: string;
}

