/**
 * API V3 - Data Etat - API externes
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiExterneError } from '../model/models';
import { HTTPValidationError } from '../model/models';
import { InfoApiEntreprise } from '../model/models';


import { aev3Configuration }                                     from '../configuration';



export interface EntrepriseServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: aev3Configuration;

    /**
     * Get Info Entreprise
     * Récupère les informations d\&#39;une entreprise à partir de son SIRET.
     * @param siret 
     */
    getInfoEntrepriseInfoEntrepriseSiretGet(siret: string, extraHttpRequestParams?: any): Observable<InfoApiEntreprise>;

}
