/**
 * API V3 - Data Etat - API externes
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { aev3Configuration }                                     from '../configuration';



export interface HealthcheckServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: aev3Configuration;

    /**
     * Vérification de la disponibilité de l\&#39;API Entreprise en mode batch
     * 
     */
    entrepriseBatchHealthcheckHealthcheckentrepriseBatchGet(extraHttpRequestParams?: any): Observable<any>;

}
