/**
 * API V3 - Data Etat - API externes
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiExterneError } from '../model/models';
import { HTTPValidationError } from '../model/models';
import { InfoApiSubvention } from '../model/models';


import { aev3Configuration }                                     from '../configuration';



export interface SubventionServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: aev3Configuration;

    /**
     * Get Info Subvention
     * 
     * @param siret 
     */
    getInfoSubventionInfoSubventionSiretGet(siret: string, extraHttpRequestParams?: any): Observable<InfoApiSubvention>;

}
